In [1]:
class demo:
    def test(self):
        print("test() for the class and method")
        return
obj=demo()
obj.test()    

test() for the class and method


In [2]:
def test():
    print("test() for function")
    return
test()

test() for function


In [10]:
class demo1:
    def fact(self,n):
        #return the factorial
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
            
        return fact
    
pl=demo1()
print(pl.fact(5))#120

120


In [22]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p2
        self.p2=p1
    def add(self,p1,p2):
            return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [40]:
class person(object):
    def __init__(self,name):
        self.name=name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
    
class employee(person):
    def isemployee(self):
        return True

emp=person("anil")
print(emp.getname(),emp.isemployee())
    
emp1=employee("akhil")
print(emp1.getname(),emp1.isemployee())

anil False
akhil True


In [42]:
lst=[1,2,3,4]
print(lst)

[1, 2, 3, 4]


In [45]:
import numpy as np
lst=[1,2,3,4]
array=np.array(lst)
print(array)

[1 2 3 4]


In [48]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack((a1,a2)))

[1 2 3 4 5 6]


In [92]:
a1=np.array([1,2,3])
a2=np.array([4,5,6])
a3=np.array([8,9,10])
print(np.vstack((a1,a2,a3([0][0][0]))))
print(geek.diag(a1,a2,a3))

TypeError: 'int' object is not subscriptable

In [95]:
np.zeros((2,2),dtype=np.int64)

array([[0, 0],
       [0, 0]], dtype=int64)

In [96]:
np.ones((4,3),dtype=np.int64)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int64)

In [3]:
import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [6]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [8]:
a1=np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])

slicing column : [2 5]


In [9]:
a1=np.array([(1,2,3),(4,5,6)])
print(a1)

[[1 2 3]
 [4 5 6]]


In [10]:
a1=np.random.normal(5,1,10)
print(a1)
print("min value=",np.min(a1))
print("max value=",np.max(a1))
print("mean value=",np.mean(a1))
print("median value=",np.median(a1))

[5.53457387 4.44635733 5.66993347 5.76101431 5.68582142 4.89378993
 4.77641861 5.70887182 3.98655434 3.61449801]
min value= 3.6144980123741917
max value= 5.7610143077889004
mean value= 5.007783312638066
median value= 5.214181901656727


In [12]:
c1=np.array([1,2])
c2=np.array([4,3])
np.dot(c1,c2)

10

In [14]:
c1=np.array([(1,2),(1,4)])
c2=np.array([(1,4),(1,2)])
np.dot(c1,c2)

array([[ 3,  8],
       [ 5, 12]])